"""
Static known-events economic calendar - FOMC decision dates, US CPI,
and US Nonfarm Payrolls release dates for 2026, sourced from the
Federal Reserve's and BLS's own published schedules (both publish
these many months ahead, so unlike a live news feed this doesn't need
a paid calendar API to be accurate) - plus US Initial Jobless Claims,
a weekly release generated by rule (every Thursday) rather than a
per-date CSV row, since a fixed weekly cadence doesn't need one.

Deliberately narrow in scope rather than a general economic calendar -
these are the events that reliably move markets across every asset
class MarketPulse covers, and a wider calendar (earnings, minor
regional data, speeches) would add noise without a paid data source to
keep it current and complete.

A rare official reschedule (it happens - see the Feb 2026 CPI date
being pushed back two days in BLS's own schedule notes, or Jobless
Claims shifting off Thursday in a Thanksgiving-week schedule) won't be
reflected here until this file/rule is manually updated.
"""

from pathlib import Path

import pandas as pd

CALENDAR_PATH = Path(__file__).resolve().parent.parent.parent / "database" / "economic_calendar.csv"

# What each event actually measures, why it moves markets, and which
# of MarketPulse's own tracked instruments tend to react most - so
# "FOMC Decision, Jul 29" reads as more than a name and a date. Not
# instrument-specific consensus/forecast numbers (that needs a paid
# data feed to stay current) - just the durable "what to watch for"
# context that doesn't change release to release.
EVENT_DETAILS = {
    "US Nonfarm Payrolls": {
        "what": "Net change in US jobs last month, plus the unemployment rate and average hourly earnings - the single most-watched US labor report.",
        "watch": "A big beat (strong jobs) tends to lift the Dollar (DX-Y.NYB) and US10Y yield (^TNX) on reduced rate-cut odds, often pressuring Gold (GC=F) and growth-heavy NASDAQ (^NDX); a big miss tends to do the opposite.",
    },
    "US CPI": {
        "what": "Headline and core month-over-month/year-over-year US inflation - the main input into the Fed's rate-decision math.",
        "watch": "A hot CPI print pushes US10Y yields and the Dollar up and typically hits NASDAQ/Gold; a cooler-than-expected print does the reverse and can fuel a broad equity rally.",
    },
    "FOMC Decision": {
        "what": "The Fed's rate decision plus its statement (and, at SEP meetings, updated dot-plot rate projections) - sets the near-term path for US interest rates.",
        "watch": "A hawkish surprise (fewer/later cuts than priced in) lifts yields and the Dollar, pressures Gold, and often hits high-multiple NASDAQ names hardest; a dovish surprise does the opposite.",
    },
    "US Initial Jobless Claims": {
        "what": "New unemployment filings for the latest week - the most frequent, most real-time read on US labor conditions between the monthly jobs reports.",
        "watch": "Usually a smaller, faster market reaction than Payrolls/CPI/FOMC - a sharp, unexpected jump can move US10Y/Dollar/equities the same directional way a weak jobs report would, but a single week rarely moves markets on its own unless it breaks a trend.",
    },
}


def _jobless_claims_rows(start, end):
    """
    Every Thursday in [start, end] - the standing weekly US Initial
    Jobless Claims release day (BLS/DOL convention; an occasional
    holiday-week shift isn't modeled here, same tolerance already
    accepted for the CSV-based events above).
    """

    first_thursday = start + pd.Timedelta(days=(3 - start.weekday()) % 7)
    thursdays = pd.date_range(first_thursday, end, freq="W-THU")

    return pd.DataFrame({
        "Date": thursdays,
        "Event": "US Initial Jobless Claims",
        "Importance": "Medium",
        "Notes": "Weekly initial claims - released every Thursday",
    })


def upcoming(days=14, reference_date=None):
    """
    Returns events from reference_date (default: today) through
    reference_date + days, ascending by date - the CSV's fixed-date
    events plus the generated weekly Jobless Claims rows. Empty
    DataFrame if the CSV is missing and no Jobless Claims Thursdays
    fall in range either.
    """

    today = pd.Timestamp(reference_date) if reference_date is not None else pd.Timestamp.now().normalize()
    cutoff = today + pd.Timedelta(days=days)

    frames = [_jobless_claims_rows(today, cutoff)]

    if CALENDAR_PATH.exists():

        df = pd.read_csv(CALENDAR_PATH, parse_dates=["Date"])
        frames.append(df[(df["Date"] >= today) & (df["Date"] <= cutoff)])

    combined = pd.concat(frames, ignore_index=True)

    return combined.sort_values("Date")


def detail_for(event_name):
    """{"what", "watch"} for a known event name, or None if it isn't in EVENT_DETAILS (an unrecognized/future event type)."""

    return EVENT_DETAILS.get(event_name)
